"""empty message

Revision ID: 0e4e5f82b645
Revises: 96b31fd5d5f7
Create Date: 2024-08-10 10:07:11.632970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e4e5f82b645'
down_revision = '96b31fd5d5f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sponsor_login', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_pic', sa.BLOB(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sponsor_login', schema=None) as batch_op:
        batch_op.drop_column('profile_pic')

    # ### end Alembic commands ###
