"""empty message

Revision ID: 96b31fd5d5f7
Revises: 
Create Date: 2024-08-09 20:46:01.388838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96b31fd5d5f7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('influencer_login',
    sa.Column('influencer_id', sa.Integer(), nullable=False),
    sa.Column('influencer_name', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('Instagram', sa.String(length=128), nullable=True),
    sa.Column('twitter', sa.String(length=128), nullable=True),
    sa.Column('youtube', sa.String(length=128), nullable=True),
    sa.Column('profile_pic', sa.BLOB(), nullable=True),
    sa.PrimaryKeyConstraint('influencer_id'),
    sa.UniqueConstraint('influencer_id'),
    sa.UniqueConstraint('influencer_name')
    )
    op.create_table('sponsor_login',
    sa.Column('sponsor_id', sa.Integer(), nullable=False),
    sa.Column('sponsor_name', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('company_name', sa.String(length=80), nullable=False),
    sa.Column('Industry', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('sponsor_id'),
    sa.UniqueConstraint('sponsor_id'),
    sa.UniqueConstraint('sponsor_name')
    )
    op.create_table('Campaigns',
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('campaign_name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('start_date', sa.DATE(), nullable=False),
    sa.Column('end_date', sa.DATE(), nullable=False),
    sa.Column('budget', sa.Integer(), nullable=False),
    sa.Column('visibility', sa.String(length=10), nullable=False),
    sa.Column('goals', sa.String(length=200), nullable=True),
    sa.Column('sponsor_name', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['sponsor_name'], ['sponsor_login.sponsor_name'], ),
    sa.PrimaryKeyConstraint('campaign_id'),
    sa.UniqueConstraint('campaign_id'),
    sa.UniqueConstraint('campaign_name')
    )
    op.create_table('flag_influencer',
    sa.Column('flag_inf_id', sa.Integer(), nullable=False),
    sa.Column('influencer_name', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['influencer_name'], ['influencer_login.influencer_name'], ),
    sa.PrimaryKeyConstraint('flag_inf_id'),
    sa.UniqueConstraint('flag_inf_id'),
    sa.UniqueConstraint('influencer_name')
    )
    op.create_table('flag_sponsor',
    sa.Column('flag_spon_id', sa.Integer(), nullable=False),
    sa.Column('sponsor_name', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['sponsor_name'], ['sponsor_login.sponsor_name'], ),
    sa.PrimaryKeyConstraint('flag_spon_id'),
    sa.UniqueConstraint('flag_spon_id'),
    sa.UniqueConstraint('sponsor_name')
    )
    op.create_table('Advertisements',
    sa.Column('ad_id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('ad_name', sa.String(length=80), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('requirements', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('images', sa.LargeBinary(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['Campaigns.campaign_id'], ),
    sa.PrimaryKeyConstraint('ad_id'),
    sa.UniqueConstraint('ad_id')
    )
    op.create_table('completed',
    sa.Column('comp_id', sa.Integer(), nullable=False),
    sa.Column('influencer_name', sa.String(length=80), nullable=False),
    sa.Column('ad_name', sa.String(length=80), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ad_name'], ['Advertisements.ad_name'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['Campaigns.campaign_id'], ),
    sa.ForeignKeyConstraint(['influencer_name'], ['influencer_login.influencer_name'], ),
    sa.PrimaryKeyConstraint('comp_id'),
    sa.UniqueConstraint('comp_id')
    )
    op.create_table('influencer_accepts',
    sa.Column('acc_id', sa.Integer(), nullable=False),
    sa.Column('influencer_name', sa.String(length=80), nullable=False),
    sa.Column('ad_name', sa.String(length=80), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ad_name'], ['Advertisements.ad_name'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['Campaigns.campaign_id'], ),
    sa.ForeignKeyConstraint(['influencer_name'], ['influencer_login.influencer_name'], ),
    sa.PrimaryKeyConstraint('acc_id'),
    sa.UniqueConstraint('acc_id')
    )
    op.create_table('influencer_requests',
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('influencer_id', sa.Integer(), nullable=False),
    sa.Column('ad_id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ad_id'], ['Advertisements.ad_id'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['Campaigns.campaign_id'], ),
    sa.ForeignKeyConstraint(['influencer_id'], ['influencer_login.influencer_id'], ),
    sa.PrimaryKeyConstraint('request_id'),
    sa.UniqueConstraint('request_id')
    )
    op.create_table('sponsor_accepts',
    sa.Column('acc_id', sa.Integer(), nullable=False),
    sa.Column('ad_name', sa.String(length=80), nullable=False),
    sa.Column('campaign_name', sa.String(length=80), nullable=False),
    sa.Column('influencer_name', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['ad_name'], ['Advertisements.ad_name'], ),
    sa.ForeignKeyConstraint(['campaign_name'], ['Campaigns.campaign_name'], ),
    sa.ForeignKeyConstraint(['influencer_name'], ['influencer_login.influencer_name'], ),
    sa.PrimaryKeyConstraint('acc_id'),
    sa.UniqueConstraint('acc_id')
    )
    op.create_table('sponsor_requests',
    sa.Column('req_id', sa.Integer(), nullable=False),
    sa.Column('ad_id', sa.Integer(), nullable=False),
    sa.Column('influencer_ids', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['ad_id'], ['Advertisements.ad_id'], ),
    sa.PrimaryKeyConstraint('req_id'),
    sa.UniqueConstraint('req_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sponsor_requests')
    op.drop_table('sponsor_accepts')
    op.drop_table('influencer_requests')
    op.drop_table('influencer_accepts')
    op.drop_table('completed')
    op.drop_table('Advertisements')
    op.drop_table('flag_sponsor')
    op.drop_table('flag_influencer')
    op.drop_table('Campaigns')
    op.drop_table('sponsor_login')
    op.drop_table('influencer_login')
    # ### end Alembic commands ###
